name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "^1.22" # Ensure Go 1.22 or later is used

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          go mod tidy

      # Step 4: Build the binary
      - name: Build the binary
        run: |
          go build -v -o k8s-microlens cmd/mapper/main.go

      # Step 5: Run tests
      - name: Run tests
        run: |
          go test -v ./tests/...
